* The goal of this outline is to create a displayable list of videos that uses URL-based indicators for which videos will be displayed in a list.
** To do this, we should use mishka chelekom components added found in lib/fos_bjj_web/components.  Specifically, a list of Card components that inhabit a scroll area component.  This scroll area should be paginated (button pagination, not infinite, using pagination.ex component) and limited to 10 cards at a time.  The cards should display a thumbnail image from the thumbnail url on the video.ex resource, as well as the description from the video underneath that, and underneath the description, the name of the technique in the video.
** We need to alter the base landing page so that it does not render the technique_tree_live component, instead having the existing welcome text and a button (Enter database) that takes users to a page that contains the new video card list on the lefthand side (75% of the screen) and the technique tree component on the righthand side (25%).
** When a technique on the technique tree is clicked, it should patch the url, which should trigger a handle_params to query the database and display videos in the cards section containing that technique.
