import Config
config :ash, policies: [show_policy_breakdowns?: true]

tailwind_watcher =
  cond do
    File.exists?("/etc/nixos/configuration.nix") and System.find_executable("tailwindcss") ->
      [
        tailwindcss:
          ~w(--input=css/app.css --output=../priv/static/assets/css/app.css --watch) ++
            [cd: Path.expand("../assets", __DIR__)]
      ]

    File.exists?("/etc/nixos/configuration.nix") ->
      []

    true ->
      [tailwind: {Tailwind, :install_and_run, [:fos_bjj, ~w(--watch)]}]
  end

# Configure your database
config :fos_bjj, FosBjj.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "fos_bjj_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fos_bjj, FosBjjWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "83V7ZveaeozceajXSFkyRfsJWWPhWXiH+v8hsnoAfSHdDEF5cNcnNvwiEKqdBo4v",
  watchers:
    [
      esbuild: {Esbuild, :install_and_run, [:fos_bjj, ~w(--sourcemap=inline --watch)]}
    ] ++ tailwind_watcher

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :fos_bjj, FosBjjWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/fos_bjj_web/router\.ex$",
      ~r"lib/fos_bjj_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :fos_bjj, dev_routes: true, token_signing_secret: "ZVpm/+bnoyOwLqa0nCe0bfgPZvFdcp9m"

# Automatically log in as dev@localhost in development
config :fos_bjj, :dev_auto_login, true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
