defmodule FosBjj.Repo.Migrations.SwitchActionsToPositionLevel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:action_positions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :action_name,
          references(:actions,
            column: :name,
            name: "action_positions_action_name_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :position_name,
          references(:positions,
            column: :name,
            name: "action_positions_position_name_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:action_positions, "action_positions_action_name_fkey")

    drop constraint(:action_positions, "action_positions_position_name_fkey")

    drop table(:action_positions)
  end
end
