defmodule FosBjj.Repo.Migrations.TechniqueRequiredFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:techniques) do
      modify :action_name, :text, null: false
      modify :orientation_name, :text, null: false
    end
  end

  def down do
    alter table(:techniques) do
      modify :orientation_name, :text, null: true
      modify :action_name, :text, null: true
    end
  end
end
