defmodule FosBjj.Repo.Migrations.MakeAttireRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      modify(:attire, :text, null: false)
    end
  end

  def down do
    alter table(:videos) do
      modify(:attire, :text, null: true)
    end
  end
end
