defmodule FosBjj.Repo.Migrations.JiuJitsuResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sub_positions, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
    end

    alter table(:technique_sub_positions) do
      modify(
        :sub_position_name,
        references(:sub_positions,
          column: :name,
          name: "technique_sub_positions_sub_position_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:technique_sub_positions, [:sub_position_name]))

    alter table(:sub_positions) do
      add(:label, :text, null: false)
      add(:position_name, :text, null: false)
    end

    create table(:positions, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
    end

    alter table(:technique_positions) do
      modify(
        :position_name,
        references(:positions,
          column: :name,
          name: "technique_positions_position_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:technique_positions, [:position_name]))

    alter table(:sub_positions) do
      modify(
        :position_name,
        references(:positions,
          column: :name,
          name: "sub_positions_position_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    alter table(:positions) do
      add(:label, :text, null: false)
    end

    create table(:orientations, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
    end

    alter table(:techniques) do
      modify(
        :orientation_name,
        references(:orientations,
          column: :name,
          name: "techniques_orientation_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:techniques, [:orientation_name]))

    alter table(:orientations) do
      add(:label, :text, null: false)
    end

    create table(:grips, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
    end

    alter table(:video_grips) do
      modify(
        :grip_name,
        references(:grips,
          column: :name,
          name: "video_grips_grip_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end

    create(index(:video_grips, [:grip_name]))

    alter table(:grips) do
      add(:label, :text, null: false)
    end
  end

  def down do
    alter table(:grips) do
      remove(:label)
    end

    drop_if_exists(index(:video_grips, [:grip_name]))

    drop(constraint(:video_grips, "video_grips_grip_name_fkey"))

    alter table(:video_grips) do
      modify(:grip_name, :text)
    end

    drop(table(:grips))

    alter table(:orientations) do
      remove(:label)
    end

    drop_if_exists(index(:techniques, [:orientation_name]))

    drop(constraint(:techniques, "techniques_orientation_name_fkey"))

    alter table(:techniques) do
      modify(:orientation_name, :text)
    end

    drop(table(:orientations))

    alter table(:positions) do
      remove(:label)
    end

    drop(constraint(:sub_positions, "sub_positions_position_name_fkey"))

    alter table(:sub_positions) do
      modify(:position_name, :text)
    end

    drop_if_exists(index(:technique_positions, [:position_name]))

    drop(constraint(:technique_positions, "technique_positions_position_name_fkey"))

    alter table(:technique_positions) do
      modify(:position_name, :text)
    end

    drop(table(:positions))

    alter table(:sub_positions) do
      remove(:position_name)
      remove(:label)
    end

    drop_if_exists(index(:technique_sub_positions, [:sub_position_name]))

    drop(constraint(:technique_sub_positions, "technique_sub_positions_sub_position_name_fkey"))

    alter table(:technique_sub_positions) do
      modify(:sub_position_name, :text)
    end

    drop(table(:sub_positions))
  end
end
