defmodule FosBjj.Repo.Migrations.AddOrientationToTechnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:techniques) do
      add(:orientation_name, :text)
    end
  end

  def down do
    alter table(:techniques) do
      remove(:orientation_name)
    end
  end
end
