defmodule FosBjj.Repo.Migrations.AddUserTrackingToResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "videos_created_by_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )

      add(
        :updated_by_id,
        references(:users,
          column: :id,
          name: "videos_updated_by_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end

    alter table(:techniques) do
      add(
        :created_by_id,
        references(:users,
          column: :id,
          name: "techniques_created_by_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )

      add(
        :updated_by_id,
        references(:users,
          column: :id,
          name: "techniques_updated_by_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:techniques, "techniques_created_by_id_fkey"))

    drop(constraint(:techniques, "techniques_updated_by_id_fkey"))

    alter table(:techniques) do
      remove(:updated_by_id)
      remove(:created_by_id)
    end

    drop(constraint(:videos, "videos_created_by_id_fkey"))

    drop(constraint(:videos, "videos_updated_by_id_fkey"))

    alter table(:videos) do
      remove(:updated_by_id)
      remove(:created_by_id)
    end
  end
end
