defmodule FosBjj.Repo.Migrations.AddVideosAndMigrateGrips do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:videos, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:url, :text, null: false)
      add(:description, :text)

      add(
        :technique_id,
        references(:techniques,
          column: :id,
          name: "videos_technique_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:video_grips, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)

      add(
        :video_id,
        references(:videos,
          column: :id,
          name: "video_grips_video_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        null: false
      )

      add(:grip_name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:video_grips, "video_grips_video_id_fkey"))

    drop(table(:video_grips))

    drop(constraint(:videos, "videos_technique_id_fkey"))

    drop(table(:videos))
  end
end
