defmodule FosBjj.Repo.Migrations.UniqueVideoIds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:videos, [:video_id], name: "videos_unique_video_id_index")
  end

  def down do
    drop_if_exists unique_index(:videos, [:video_id], name: "videos_unique_video_id_index")
  end
end
