defmodule :"Elixir.FosBjj.Repo.Migrations.ChangeVideoData-handling" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename(table(:videos), :url, to: :video_id)

    alter table(:videos) do
      add(:thumbnail_url, :text)
    end
  end

  def down do
    alter table(:videos) do
      remove(:thumbnail_url)
    end

    rename(table(:videos), :video_id, to: :url)
  end
end
