defmodule FosBjj.Repo.Migrations.RolesTextFkey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:users, "users_role_name_fkey"))

    alter table(:users) do
      modify(:role_name, :text)
    end

    create(index(:users, [:role_name]))
  end

  def down do
    drop_if_exists(index(:users, [:role_name]))

    alter table(:users) do
      modify(
        :role_name,
        references(:roles,
          column: :name,
          name: "users_role_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end
end
