defmodule FosBjj.Repo.Migrations.TechniquesAndJoinTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:techniques, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:technique_sub_positions, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)

      add(
        :technique_id,
        references(:techniques,
          column: :id,
          name: "technique_sub_positions_technique_id_fkey",
          type: :bigint,
          prefix: "public"
        ), null: false)

      add(:sub_position_name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:technique_positions, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)

      add(
        :technique_id,
        references(:techniques,
          column: :id,
          name: "technique_positions_technique_id_fkey",
          type: :bigint,
          prefix: "public"
        ), null: false)

      add(:position_name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:technique_positions, "technique_positions_technique_id_fkey"))

    drop(table(:technique_positions))

    drop(constraint(:technique_sub_positions, "technique_sub_positions_technique_id_fkey"))

    drop(table(:technique_sub_positions))

    drop(table(:techniques))
  end
end
