defmodule FosBjj.Repo.Migrations.ChangeTechniqueVideoToManyToMany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:videos, "videos_technique_id_fkey"))

    alter table(:videos) do
      modify(:technique_id, :bigint)
    end

    create(index(:videos, [:technique_id]))
  end

  def down do
    drop_if_exists(index(:videos, [:technique_id]))

    alter table(:videos) do
      modify(
        :technique_id,
        references(:techniques,
          column: :id,
          name: "videos_technique_id_fkey",
          type: :bigint,
          prefix: "public"
        )
      )
    end
  end
end
