defmodule FosBjj.Repo.Migrations.FixTypoInLastMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:video_techniques, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)

      add(
        :video_id,
        references(:videos,
          column: :id,
          name: "video_techniques_video_id_fkey",
          type: :bigint,
          prefix: "public"
        ), null: false)

      add(
        :technique_id,
        references(:techniques,
          column: :id,
          name: "video_techniques_technique_id_fkey",
          type: :bigint,
          prefix: "public"
        ), null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:video_techniques, "video_techniques_video_id_fkey"))

    drop(constraint(:video_techniques, "video_techniques_technique_id_fkey"))

    drop(table(:video_techniques))
  end
end
