defmodule FosBjj.Repo.Migrations.AddPositionOrientation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:position_orientations, primary_key: false) do
      add(
        :position_name,
        references(:positions,
          column: :name,
          name: "position_orientations_position_name_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(
        :orientation_name,
        references(:orientations,
          column: :name,
          name: "position_orientations_orientation_name_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:position_orientations, "position_orientations_position_name_fkey"))

    drop(constraint(:position_orientations, "position_orientations_orientation_name_fkey"))

    drop(table(:position_orientations))
  end
end
