defmodule FosBjj.Repo.Migrations.BjjActions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:techniques) do
      add :action_name, :text
    end

    create table(:actions, primary_key: false) do
      add :name, :text, null: false, primary_key: true
    end

    alter table(:techniques) do
      modify :action_name,
             references(:actions,
               column: :name,
               name: "techniques_action_name_fkey",
               type: :text,
               prefix: "public"
             )
    end

    alter table(:actions) do
      add :label, :text, null: false
    end

    create table(:action_sub_positions, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :action_name,
          references(:actions,
            column: :name,
            name: "action_sub_positions_action_name_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :sub_position_name,
          references(:sub_positions,
            column: :name,
            name: "action_sub_positions_sub_position_name_fkey",
            type: :text,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:action_sub_positions, "action_sub_positions_action_name_fkey")

    drop constraint(:action_sub_positions, "action_sub_positions_sub_position_name_fkey")

    drop table(:action_sub_positions)

    alter table(:actions) do
      remove :label
    end

    drop constraint(:techniques, "techniques_action_name_fkey")

    alter table(:techniques) do
      modify :action_name, :text
    end

    drop table(:actions)

    alter table(:techniques) do
      remove :action_name
    end
  end
end
