defmodule FosBjj.Repo.Migrations.ChangeTechniqueSubpositionRelationshipToSingle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:techniques) do
      add(
        :sub_position_name,
        references(:sub_positions,
          column: :name,
          name: "techniques_sub_position_name_fkey",
          type: :text,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:techniques, "techniques_sub_position_name_fkey"))

    alter table(:techniques) do
      remove(:sub_position_name)
    end
  end
end
