defmodule FosBjj.Repo.Migrations.AddAttireToVideos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add(:attire, :text)
    end
  end

  def down do
    alter table(:videos) do
      remove(:attire)
    end
  end
end
