defmodule FosBjj.Repo.Migrations.RemoveTechIdOnVideos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      remove(:technique_id)
    end
  end

  def down do
    alter table(:videos) do
      add(:technique_id, :bigint, null: false)
    end
  end
end
