defmodule FosBjj.Repo.Migrations.AddRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Create roles table first
    create table(:roles, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
      add(:label, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    # Seed the default roles before adding FK constraint
    execute("INSERT INTO roles (name, label) VALUES ('admin', 'Administrator')")
    execute("INSERT INTO roles (name, label) VALUES ('coach', 'Coach')")
    execute("INSERT INTO roles (name, label) VALUES ('student', 'Student')")

    # Add role_name column to users
    alter table(:users) do
      add(:role_name, :text, default: "student")
    end

    # Now add the FK constraint
    alter table(:users) do
      modify(
        :role_name,
        references(:roles,
          column: :name,
          name: "users_role_name_fkey",
          type: :text,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:users, "users_role_name_fkey"))

    alter table(:users) do
      remove(:role_name)
    end

    drop(table(:roles))
  end
end
