defmodule FosBjj.Repo.Migrations.AddVideoReportReasonsConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:video_report_reasons, primary_key: false) do
      add :name, :text, null: false, primary_key: true
      add :label, :text, null: false
    end

    alter table(:user_video_reports) do
      remove :reason

      add :reason_name,
          references(:video_report_reasons,
            column: :name,
            name: "user_video_reports_reason_name_fkey",
            type: :text,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_video_reports, "user_video_reports_reason_name_fkey")

    alter table(:user_video_reports) do
      remove :reason_name
      add :reason, :text, null: false
    end

    drop table(:video_report_reasons)
  end
end
