defmodule FosBjj.Repo.Migrations.UpdatedByOnCoachApp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:coach_applications) do
      add :updated_by_id,
          references(:users,
            column: :id,
            name: "coach_applications_updated_by_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:coach_applications, "coach_applications_updated_by_id_fkey")

    alter table(:coach_applications) do
      remove :updated_by_id
    end
  end
end
