defmodule FosBjj.Repo.Migrations.AddUserVideoReports do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_video_reports, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :reason, :text, null: false
      add :message, :text
      add :resolved, :boolean, null: false, default: false
      add :admin_resolution_reason, :text
      add :resolution_outcome, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_video_reports_user_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :video_id,
          references(:videos,
            column: :id,
            name: "user_video_reports_video_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_video_reports, "user_video_reports_user_id_fkey")

    drop constraint(:user_video_reports, "user_video_reports_video_id_fkey")

    drop table(:user_video_reports)
  end
end
