defmodule FosBjj.Repo.Migrations.AddMessageGroupIdToUserMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_messages) do
      add :message_group_id, :uuid
    end

    execute(
      "UPDATE user_messages SET message_group_id = gen_random_uuid() WHERE message_group_id IS NULL"
    )

    alter table(:user_messages) do
      modify :message_group_id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    create index(:user_messages, [:sender_id, :message_group_id])
  end

  def down do
    drop_if_exists index(:user_messages, [:sender_id, :message_group_id])

    alter table(:user_messages) do
      remove :message_group_id
    end
  end
end
