defmodule FosBjj.Repo.Migrations.AddUserNameToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add column as nullable first
    alter table(:users) do
      add :user_name, :text, null: true
    end

    # Set existing users' username to their email
    execute "UPDATE users SET user_name = email WHERE user_name IS NULL"

    # Now add the NOT NULL constraint
    alter table(:users) do
      modify :user_name, :text, null: false
    end

    create unique_index(:users, [:user_name], name: "users_unique_user_name_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:user_name], name: "users_unique_user_name_index")

    alter table(:users) do
      remove :user_name
    end
  end
end
