defmodule FosBjj.Repo.Migrations.AddSharedVideoToUserMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_messages) do
      add :shared_video_id,
          references(:videos,
            column: :id,
            name: "user_messages_shared_video_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:user_messages, "user_messages_shared_video_id_fkey")

    alter table(:user_messages) do
      remove :shared_video_id
    end
  end
end
