defmodule FosBjj.Repo.Migrations.RemoveUnwantedUniqueVideoId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:video_notes, [:video_id],
                     name: "video_notes_unique_video_id_index"
                   )
  end

  def down do
    create unique_index(:video_notes, [:video_id], name: "video_notes_unique_video_id_index")
  end
end
