defmodule FosBjj.Repo.Migrations.AddAddressLine2ToAcademies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:academies) do
      add :address_line_2, :text
    end
  end

  def down do
    alter table(:academies) do
      remove :address_line_2
    end
  end
end
