defmodule FosBjj.Repo.Migrations.RenameCoachApplicationsToContributorApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:coach_applications), to: table(:contributor_applications)

    execute(
      "ALTER TABLE contributor_applications RENAME CONSTRAINT coach_applications_user_id_fkey TO contributor_applications_user_id_fkey"
    )

    execute(
      "ALTER TABLE contributor_applications RENAME CONSTRAINT coach_applications_updated_by_id_fkey TO contributor_applications_updated_by_id_fkey"
    )
  end

  def down do
    execute(
      "ALTER TABLE contributor_applications RENAME CONSTRAINT contributor_applications_user_id_fkey TO coach_applications_user_id_fkey"
    )

    execute(
      "ALTER TABLE contributor_applications RENAME CONSTRAINT contributor_applications_updated_by_id_fkey TO coach_applications_updated_by_id_fkey"
    )

    rename table(:contributor_applications), to: table(:coach_applications)
  end
end
