defmodule FosBjj.Repo.Migrations.TypesOnUserMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_messages) do
      add :type, :text, null: false, default: "system_notification"
    end

    execute("""
    UPDATE user_messages
    SET type = 'video_shared_by_coach'
    WHERE shared_video_id IS NOT NULL
    """)
  end

  def down do
    alter table(:user_messages) do
      remove :type
    end
  end
end
