defmodule FosBjj.Repo.Migrations.AddCoachApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:coach_applications, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :body, :text, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "coach_applications_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:coach_applications, "coach_applications_user_id_fkey")

    drop table(:coach_applications)
  end
end
