defmodule FosBjj.Repo.Migrations.RemoveUnneededPkeyForConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DELETE FROM action_sub_position_orientations a
    USING (
      SELECT
        ctid,
        row_number() OVER (
          PARTITION BY action_name, sub_position_name, orientation_name
          ORDER BY id
        ) AS row_num
      FROM action_sub_position_orientations
    ) dedup
    WHERE a.ctid = dedup.ctid
      AND dedup.row_num > 1
    """)

    drop constraint("action_sub_position_orientations", "action_sub_position_orientations_pkey")

    alter table(:action_sub_position_orientations) do
      modify :orientation_name, :text, primary_key: true
      modify :sub_position_name, :text, primary_key: true
      modify :action_name, :text, primary_key: true
      remove :id
    end
  end

  def down do
    drop constraint("action_sub_position_orientations", "action_sub_position_orientations_pkey")

    alter table(:action_sub_position_orientations) do
      add :id, :bigserial, null: false, primary_key: true
      modify :action_name, :text, primary_key: false
      modify :sub_position_name, :text, primary_key: false
      modify :orientation_name, :text, primary_key: false
    end
  end
end
