defmodule FosBjj.Repo.Migrations.AcademyMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :bjj_belt, :text
      add :other_high_level_experience, :boolean, null: false, default: false
    end

    create table(:academy_users, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :academy_id, :bigint, null: false
      add :user_id, :bigint, null: false
    end

    create table(:academies, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:academy_users) do
      modify :academy_id,
             references(:academies,
               column: :id,
               name: "academy_users_academy_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "academy_users_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create unique_index(:academy_users, [:user_id, :academy_id],
             name: "academy_users_unique_user_academy_index"
           )

    alter table(:academies) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:academies) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop_if_exists unique_index(:academy_users, [:user_id, :academy_id],
                     name: "academy_users_unique_user_academy_index"
                   )

    drop constraint(:academy_users, "academy_users_academy_id_fkey")

    drop constraint(:academy_users, "academy_users_user_id_fkey")

    alter table(:academy_users) do
      modify :user_id, :bigint
      modify :academy_id, :bigint
    end

    drop table(:academies)

    drop table(:academy_users)

    alter table(:users) do
      remove :other_high_level_experience
      remove :bjj_belt
    end
  end
end
