defmodule FosBjj.Repo.Migrations.ActionVideosPt1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:videos) do
      add :ready, :boolean, null: false, default: true
      add :source_type, :text, null: false, default: "youtube"
      add :hosted_video_url, :text
    end

    create table(:in_action_staging, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :source_url, :text, null: false
      add :source_video_id, :text, null: false
      add :start_seconds, :bigint, null: false
      add :end_seconds, :bigint, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :video_id,
          references(:videos,
            column: :id,
            name: "in_action_staging_video_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :created_by_id,
          references(:users,
            column: :id,
            name: "in_action_staging_created_by_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :updated_by_id,
          references(:users,
            column: :id,
            name: "in_action_staging_updated_by_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:in_action_staging, [:video_id],
             name: "in_action_staging_unique_video_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:in_action_staging, [:video_id],
                     name: "in_action_staging_unique_video_id_index"
                   )

    drop constraint(:in_action_staging, "in_action_staging_video_id_fkey")

    drop constraint(:in_action_staging, "in_action_staging_created_by_id_fkey")

    drop constraint(:in_action_staging, "in_action_staging_updated_by_id_fkey")

    drop table(:in_action_staging)

    alter table(:videos) do
      remove :hosted_video_url
      remove :source_type
      remove :ready
    end
  end
end
