defmodule FosBjj.Repo.Migrations.UserVideoNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:video_notes, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :video_timestamp, :bigint
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "video_notes_user_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :video_id,
          references(:videos,
            column: :id,
            name: "video_notes_video_id_fkey",
            type: :bigint,
            prefix: "public"
          )
    end

    create unique_index(:video_notes, [:video_id], name: "video_notes_unique_video_id_index")
  end

  def down do
    drop_if_exists unique_index(:video_notes, [:video_id],
                     name: "video_notes_unique_video_id_index"
                   )

    drop constraint(:video_notes, "video_notes_user_id_fkey")

    drop constraint(:video_notes, "video_notes_video_id_fkey")

    drop table(:video_notes)
  end
end
