defmodule FosBjj.Repo.Migrations.InActionProcessingState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:in_action_staging) do
      add :processed_at, :utc_datetime_usec
      add :failed_at, :utc_datetime_usec
      add :failure_reason, :text
      add :storage_key, :text
    end
  end

  def down do
    alter table(:in_action_staging) do
      remove :storage_key
      remove :failure_reason
      remove :failed_at
      remove :processed_at
    end
  end
end
