defmodule FosBjj.Repo.Migrations.AddPrimaryToAcademyUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:academy_users) do
      add :primary, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:academy_users) do
      remove :primary
    end
  end
end
