defmodule FosBjj.Repo.Migrations.AddStudentCoachRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:student_coach_relationships, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :learner_id,
          references(:users,
            column: :id,
            name: "student_coach_relationships_learner_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :coach_id,
          references(:users,
            column: :id,
            name: "student_coach_relationships_coach_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:student_coach_relationships, [:learner_id, :coach_id],
             name: "student_coach_relationships_unique_learner_coach_index"
           )
  end

  def down do
    drop_if_exists unique_index(:student_coach_relationships, [:learner_id, :coach_id],
                     name: "student_coach_relationships_unique_learner_coach_index"
                   )

    drop constraint(:student_coach_relationships, "student_coach_relationships_learner_id_fkey")

    drop constraint(:student_coach_relationships, "student_coach_relationships_coach_id_fkey")

    drop table(:student_coach_relationships)
  end
end
