defmodule FosBjj.Repo.Migrations.MakeUserMessageBodyNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_messages) do
      modify :body, :text, null: true
    end
  end

  def down do
    alter table(:user_messages) do
      modify :body, :text, null: false
    end
  end
end
