defmodule FosBjj.Repo.Migrations.AddUserMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_messages, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :body, :text, null: false
      add :received, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sender_id,
          references(:users,
            column: :id,
            name: "user_messages_sender_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :recipient_id,
          references(:users,
            column: :id,
            name: "user_messages_recipient_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:user_messages, "user_messages_sender_id_fkey")

    drop constraint(:user_messages, "user_messages_recipient_id_fkey")

    drop table(:user_messages)
  end
end
