defmodule FosBjj.Repo.Migrations.AddLocationToAcademies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:academies) do
      add :address_line_1, :text
      add :city, :text
      add :state, :text
      add :zip, :text
      add :country, :text
    end
  end

  def down do
    alter table(:academies) do
      remove :country
      remove :zip
      remove :state
      remove :city
      remove :address_line_1
    end
  end
end
