defmodule FosBjj.Repo.Migrations.AddVideoTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:video_types, primary_key: false) do
      add :name, :text, null: false, primary_key: true
      add :label, :text, null: false
    end

    execute("INSERT INTO video_types (name, label) VALUES ('instructional', 'Instructional')")
    execute("INSERT INTO video_types (name, label) VALUES ('analysis', 'Analysis')")

    alter table(:videos) do
      add :video_type_name, :text, null: false, default: "instructional"
    end

    alter table(:videos) do
      modify :video_type_name,
             references(:video_types,
               column: :name,
               name: "videos_video_type_name_fkey",
               type: :text,
               prefix: "public"
             )
    end
  end

  def down do
    alter table(:video_types) do
      remove :label
    end

    drop constraint(:videos, "videos_video_type_name_fkey")

    alter table(:videos) do
      modify :video_type_name, :text
    end

    drop table(:video_types)

    alter table(:videos) do
      remove :video_type_name
    end
  end
end
