name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.19.4'
          otp-version: '28.1.1'

      - name: Cache Deps & Build
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: |
          mix deps.get --only prod
          mix compile

      - name: Build Assets
        run: |
          mix assets.deploy

      - name: Build Release
        run: |
          MIX_ENV=prod mix release --overwrite

      - name: Package Release
        run: tar -czf release.tar.gz -C _build/prod/rel/fos_bjj .

      - name: Copy Release to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "release.tar.gz"
          target: "/tmp"

      - name: Execute Remote Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            /usr/local/bin/finish_deploy.sh
